# -*- coding: utf-8 -*-
$:.unshift("/Library/RubyMotion/lib")
$:.unshift("~/.rubymotion/rubymotion-templates")
require 'motion/project/template/ios'

require 'rubygems'
# require 'motion-cocoapods'
require 'bundler'
Bundler.require

Motion::Project::App.setup do |app|
  # Use `rake config' to see complete project settings.
  app.name = 'TestCocoaPodsResource'
  app.archs['iPhoneOS'] = ['arm64']
  app.pods do
    pod 'QBImagePickerController', '= 1.0'
  end
end
